-- 스키마 생성
CREATE SCHEMA `jolbu`
DEFAULT CHARACTER SET utf8mb4
collate utf8mb4_general_ci

-- 유저 테이블
DROP TABLE TB_USER;
CREATE TABLE TB_USER (
   USER_NO INTEGER PRIMARY KEY AUTO_INCREMENT,
   ID VARCHAR(32) NOT NULL,
   NAME VARCHAR(32) NOT NULL,
   EMAIL VARCHAR(32) NOT NULL,
   PASSWORD VARCHAR(200) NOT NULL,
   ADMIN INT NOT NULL,
   SOCIAL INT NOT NULL,
   PNS VARCHAR(200) NOT NULL
) COMMENT = '회원정보'
ENGINE = InnoDB;

-- 검색 테이블
DROP TABLE TB_SEARCH;
CREATE TABLE TB_SEARCH (
   USER_NO INT,
   FOREIGN KEY (USER_NO) REFERENCES TB_USER(USER_NO),
   SEARCH_CON VARCHAR(200) NOT NULL
) COMMENT = '검색'
ENGINE = InnoDB;

-- 나의주식
DROP TABLE TB_MYSTOCK;
CREATE TABLE TB_MYSTOCK (
   USER_NO INT,
   FOREIGN KEY (USER_NO) REFERENCES TB_USER(USER_NO),
   STOCK_NAME VARCHAR(200) NOT NULL,
   STOCK_AICONTENT VARCHAR(500)
) COMMENT = '나의주식'
ENGINE = InnoDB;

-- 주식가격
CREATE TABLE TB_STOCK (
code varchar(50) not null unique,
opening_price INT,
high_price INT,
low_price INT,
trade_price INT)
COMMENT = '주식가격'
engine=InnoDB;