-- 스키마 생성
CREATE SCHEMA `jolbu`
DEFAULT CHARACTER SET utf8mb4
collate utf8mb4_general_ci

-- 유저 테이블
DROP TABLE TB_USER;
CREATE TABLE TB_USER (
USER_NO INTEGER PRIMARY KEY AUTO_INCREMENT,
ID VARCHAR(50) NOT NULL,
NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50),
PASSWORD VARCHAR(200),
ADMIN INT NOT NULL DEFAULT 0,
SOCIAL INT NOT NULL DEFAULT 0,
PNS VARCHAR(200) DEFAULT NULL
) COMMENT = '회원정보'
ENGINE = InnoDB;


--유저 테이블 수정 24-01-24
ALTER TABLE TB_USER MODIFY COLUMN ADMIN INT NOT NULL DEFAULT 0; --어드민 DEFAULT값추가

ALTER TABLE TB_USER MODIFY COLUMN SOCIAL INT NOT NULL DEFAULT 0; --소셜 DEFAULT값추가

ALTER TABLE TB_USER MODIFY COLUMN PASSWORD VARCHAR(200); --패스워드 NULL 가능 추가

ALTER TABLE TB_USER MODIFY COLUMN ID VARCHAR(50) NOT NULL;  -- ID NAME EMAIL 글자 제한 완화 24-01-24 PM 3:20

ALTER TABLE TB_USER MODIFY COLUMN NAME VARCHAR(50) NOT NULL;

ALTER TABLE TB_USER MODIFY COLUMN EMAIL VARCHAR(50);

-- 관리자 24-01-24 추가
DROP TABLE TB_ADMIN;
CREATE TABLE TB_ADMIN (
   USER_NO INT,
   FOREIGN KEY (USER_NO) REFERENCES TB_USER(USER_NO),
   ADMIN_QNA_NO INT PRIMARY KEY AUTO_INCREMENT,
   ADMIN_QNA_NAME VARCHAR(600),
   ADMIN_QNA_CONTENT VARCHAR(2000)
   ) COMMENT = '관리자'
   ENGINE = InnoDB;

-- 검색 테이블
DROP TABLE TB_SEARCH;
CREATE TABLE TB_SEARCH (
   USER_NO INT,
   FOREIGN KEY (USER_NO) REFERENCES TB_USER(USER_NO),
   SEARCH_CON VARCHAR(200) NOT NULL
) COMMENT = '검색'
ENGINE = InnoDB;

-- 나의주식
DROP TABLE TB_MYSTOCK;
CREATE TABLE TB_MYSTOCK (
   USER_NO INT,
   FOREIGN KEY (USER_NO) REFERENCES TB_USER(USER_NO),
   STOCK_NAME VARCHAR(200) NOT NULL,
   STOCK_AICONTENT VARCHAR(500)
) COMMENT = '나의주식'
ENGINE = InnoDB;

-- 주식가격
DROP TABLE TB_STOCK;
CREATE TABLE TB_STOCK (
code varchar(50) not null unique,
opening_price INT,
high_price INT,
low_price INT,
trade_price INT)
COMMENT = '주식가격'
engine=InnoDB;
